//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEmpDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Users = new HashSet<User>();
        }
    
        public int DeptId { get; set; }
        public string DeptName { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
